default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: kinbox
    username: kinbox_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: kinbox
    username: kinbox_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: kinbox
    username: kinbox_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: kinbox
    username: kinbox_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>
