default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  database: kinbox
  username: kinbox_user
  password: <%= ENV['postgresql://kinbox_user:WX1JRa65b578oHqPav9Uu3Nbt418HI29@dpg-d5jln29r0fns73d6mgag-a/kinbox'] %>
  url: <%= ENV['DATABASE_URL'] %>